### ISSUE TITLE
Suggestion: allow using integer type for sqlite backend

### ISSUE THREAD

**Issue by tech6hutch** [adwhit/diesel-derive-enum#51]
The ability to use Integer instead of Text for the SQL representation of enums when using the sqlite backend would be useful. It wouldn't be as statically type safe without the check clause, but it would be more efficient than using strings.

**Comment by adwhit** [comment]
It's a nice idea, I guess, but a bit too niche for this crate IMO. I may be wrong but I suspect that most people using `sqlite` are doing so for convenience rather than performance. Would be interested if anyone else has wanted this feature.

In terms of implementation, I am wary about adding too many configuration options, but maybe it could be done as a separate feature e.g. `sqlite-integer`

**Comment by tech6hutch** [comment]
I ended up switching to postgres anyway, but I'll leave this open in case anyone else wants it I guess

**Comment by adwhit** [comment]
I think this is out-of-scope

**Comment by boehs** [comment]
> Would be interested to hear if anyone else has wanted this feature.

Hi, it's been a hot minute but I'd love this!
